### ISSUE TITLE
Upper boundary to ESLint version in package.json

### ISSUE THREAD

**Issue by xbill82** [gyandeeps/gruntify-eslint#17]
Hi,
I see that the current dependency for eslint is `>=0.24.1`. This is nice, but we recently hit an API change that broke our tests (one config param was renamed and all the tests failed). How about blocking the ESLint dependency version and binding it to the plugin version? (i.e. only bumping the dep version when bumping the plugin).

Thanks!

**Comment by gyandeeps** [comment]
Agreed. Please send in a PR for this then i will release `1.3.1` which sticks to eslint@1.x and do a separate release for eslint@2.x

**Comment by WRidder** [comment]
Agreed. Bumped into the same error. Upper boundary is welcome.

**Comment by gyandeeps** [comment]
Fixed with https://github.com/gyandeeps/gruntify-eslint/pull/18

**Comment by gyandeeps** [comment]
New version 1.3.1 has been released.

**Comment by gyandeeps** [comment]
To use Eslint 2.x use gruntify-eslint 2.0
