### ISSUE TITLE
grunt-contrib is reserved

### ISSUE THREAD

**Issue by Nate-Wilkins** [gyandeeps/gruntify-eslint#2]
The `grunt-contrib` [namespace is reserved to the grunt team](http://gruntjs.com/creating-plugins#naming-your-task) for common tasks that most of the community usually always uses in their projects. It'd be nice if this module name was a custom one so we as consumers can differentiate.

Partially related to #1

**Comment by Askelkana** [comment]
Why 'gruntify-eslint' and not 'grunt-eslint' which would have been the standard way to name it? For example, now the load-grunt-tasks job cannot find this, so a separate call to load this plugin is required. It's needlessly sloppy, IMO.
