### ISSUE TITLE
Ignoring folders

### ISSUE THREAD

**Issue by techpines** [gyandeeps/gruntify-eslint#20]
Is there any way to ignore files?

I have something like this:

```js
eslint: {
  src: ['src/**/*.js']
}
```

But I also have folder called `vendor` for third party libs that is in the same folder.  Is there any way to ignore that folder?

**Comment by gyandeeps** [comment]
you can add `.eslintignore` file with all the ignores.
http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

**Comment by techpines** [comment]
Thanks @gyandeeps , and I also found that this worked:

```js
eslint: {
  src: ['src/**/*.js', '!src/**/vendor/*.js]
}
```
