### ISSUE TITLE
Means to disable ancestor `.eslintrc` inheritance?

### ISSUE THREAD

**Issue by brettz9** [gyandeeps/gruntify-eslint#21]
I'm working on a Git repo inside of another Git repo, so I don't want gruntify-eslint to check for the `.eslintrc` ancestors.

I've tried setting `configFile` under `options` but this doesn't help. Is there any means of avoiding this cascading upward?

Thanks!

**Comment by gyandeeps** [comment]
@brettz9 Sorry for the late response. But you can set `root: true` inside the child project's .eslinrc file.

**Comment by gyandeeps** [comment]
Feel free to reopen if the issue still persists.
