### ISSUE TITLE
Compatibility with eslint 3.x

### ISSUE THREAD

**Issue by fiducioso-dan** [gyandeeps/gruntify-eslint#23]
Currently depends on eslint 2.x, but 3.0.0 [was released](http://eslint.org/blog/2016/07/eslint-v3.0.0-released) on 2017-07-01

**Comment by gyandeeps** [comment]
@fiducioso-dan You want to send a PR for this?

**Comment by fiducioso-dan** [comment]
@gyandeeps Sorry I don't currently have permission from my employer to make code contributions to the project, just bug reports.

**Comment by gyandeeps** [comment]
ah ok. I will make the change and release a 3.0 version.

**Comment by gyandeeps** [comment]
@fiducioso-dan Done and released https://github.com/gyandeeps/gruntify-eslint/releases/tag/v3.0.0
