### ISSUE TITLE
Deprecate "grunt-contrib-eslint"

### ISSUE THREAD

**Issue by Krinkle** [gyandeeps/gruntify-eslint#27]
Could you mark this package as deprecated in npm? Right now shows up in various places when searching for "grunt eslint". While that may take longer to change, at least having the resulting page on npmjs.org route users to the new name would help.

> https://www.npmjs.com/package/grunt-contrib-eslint
> Source code: <https://github.com/gyandeeps/grunt-contrib-eslint> (redirects to here, <https://github.com/gyandeeps/gruntify-eslint>)

<img height="302" alt="screen shot 2016-12-16 at 23 17 28" src="https://cloud.githubusercontent.com/assets/156867/21285152/d83ba2b2-c3e5-11e6-86b2-1f85336a2388.png">

See also:
* #9
* <https://docs.npmjs.com/cli/deprecate>

**Comment by fgaleano** [comment]
Curious, what other package are people using for ESLint in Grunt? Looking to implement it now for a project.

**Comment by RinkAttendant6** [comment]
Regarding https://github.com/gyandeeps/gruntify-eslint/issues/27#issuecomment-283144369: https://www.npmjs.com/package/grunt-eslint

**Comment by calvinjuarez** [comment]
Seems like this can be closed.

![screen shot 2018-06-15 at 17 34 45](https://user-images.githubusercontent.com/2146819/41493236-6c22c46c-70c2-11e8-9481-bb6bd9edf0c3.png)

**Comment by Krinkle** [comment]
Thanks!
