### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by sindresorhus** [gyandeeps/gruntify-eslint#5]
This already exists: https://github.com/sindresorhus/grunt-eslint

The `grunt-contrib` prefix is also reserved for officially supported plugins in the https://github.com/gruntjs/ org.

**Comment by eddiemonge** [comment]
but not changed in npm

**Comment by gyandeeps** [comment]
@eddiemonge Those are the old releases. The new releases are all on the new name.

**Comment by eddiemonge** [comment]
Can you mark that as deprecated or unpublish it so its not confusing please?

**Comment by gyandeeps** [comment]
It has a deprecation notice when you try to install it. No I cant remove it as it might break for people who might use it.

**Comment by eddiemonge** [comment]
You should also add a deprecation notice in the readme so it shows on the npm search page
