### ISSUE TITLE
Dynamic altering `src` does not affected linted files

### ISSUE THREAD

**Issue by dmtrs** [gyandeeps/gruntify-eslint#6]
I am using `gruntify-eslint` along with `grunt-contrib-watch` and I have the following snippet in my `Gruntfile.js`:

```js
    grunt.event.on('watch', function(action, filepath) {
        grunt.config('eslint.src', filepath);
    });
```

In order to lint only files altered and not all the project. Unfortunately it does not seem to work for `gruntify-eslint`

**Comment by gyandeeps** [comment]
Can you please share your gruntfile specially the part where you have your eslint configured. How to does watch calls it again. I have never used grunt watch that why I want more info.
Thanks

**Comment by dmtrs** [comment]
Was wrong configuration from my side. For future use `grunt-contrib-watch` `spawn` flag should be false
